<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache.curator</groupId>
        <artifactId>apache-curator</artifactId>
        <version>5.9.0</version>
    </parent>

    <artifactId>curator-test</artifactId>
    <version>5.9.0-lineaje-01</version>

    <name>Curator Testing</name>
    <description>Unit testing utilities.</description>
    <inceptionYear>2011</inceptionYear>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <dependency.locations.enabled>false</dependency.locations.enabled>
        <currentStableVersion>5.7.1</currentStableVersion>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.resourceEncoding>UTF-8</project.build.resourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <short-jdk-version>8</short-jdk-version>
        <jdk-version>1.${short-jdk-version}</jdk-version>
        <redirectTestOutputToFile>true</redirectTestOutputToFile>
        <zookeeper-version>3.9.3</zookeeper-version>
        <maven-bundle-plugin-version>5.1.4</maven-bundle-plugin-version>
        <maven-compiler-plugin-version>3.10.0</maven-compiler-plugin-version>
        <maven-dependency-plugin-version>3.2.0</maven-dependency-plugin-version>
        <maven-project-info-reports-plugin-version>3.0.0</maven-project-info-reports-plugin-version>
        <maven-javadoc-plugin-version>3.3.2</maven-javadoc-plugin-version>
        <maven-surefire-plugin-version>3.0.0-M5</maven-surefire-plugin-version>
        <spotless.version>2.39.0</spotless.version>
        <doxia-module-confluence-version>1.11.1</doxia-module-confluence-version>
        <javassist-version>3.24.1-GA</javassist-version>
        <commons-math-version>2.2</commons-math-version>
        <jackson-mapper-asl-version>1.9.13</jackson-mapper-asl-version>
        <jackson-version>2.18.1</jackson-version>
        <assertj-version>3.23.1</assertj-version>
        <jersey-version>1.19.4</jersey-version>
        <jsr311-api-version>1.1.1</jsr311-api-version>
        <jaxb-version>2.2.11</jaxb-version>
        <javax-activation-version>1.1.1</javax-activation-version>
        <jetty-version>9.4.57.v20241219</jetty-version>
        <scannotation-version>1.0.2</scannotation-version>
        <resteasy-jaxrs-version>2.3.5.Final</resteasy-jaxrs-version>
        <guava-version>32.0.0-jre</guava-version>
        <guava-listenablefuture-version>9999.0-empty-to-avoid-conflict-with-guava</guava-listenablefuture-version>
        <guava-failureaccess-version>1.0.1</guava-failureaccess-version>
        <junit-version>5.6.2</junit-version>
        <swift-version>0.23.1</swift-version>
        <maven-shade-plugin-version>3.2.4</maven-shade-plugin-version>
        <slf4j-version>1.7.25</slf4j-version>
        <clirr-maven-plugin-version>2.8</clirr-maven-plugin-version>
        <dropwizard-version>3.2.5</dropwizard-version>
        <snappy-version>1.1.10.4</snappy-version>
        <build-helper-maven-plugin-version>3.3.0</build-helper-maven-plugin-version>
        <awaitility-version>4.1.1</awaitility-version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
        </dependency>

        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <id>apache-curator-guava-shader</id>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>com.google.guava:guava</include>
                                    <include>com.google.guava:listenablefuture</include>
                                    <include>com.google.guava:failureaccess</include>
                                </includes>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>com.google</pattern>
                                    <shadedPattern>org.apache.curator-test.shaded.com.google</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google</pattern>
                                    <shadedPattern>org.apache.curator-test.shaded.com.google</shadedPattern>
                                    <includes>
                                        <include>com.google.common.base.Function</include>
                                        <include>com.google.common.base.Predicate</include>
                                        <include>com.google.common.reflect.TypeToken</include>
                                    </includes>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <threadCount>1</threadCount>
                    <reuseForks>false</reuseForks>
                    <redirectTestOutputToFile>true</redirectTestOutputToFile>
                </configuration>
            </plugin>
        </plugins>
    </build>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-handler</artifactId>
        <version>4.2.5.Final</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
